### ISSUE TITLE
Screensaver Prevents Turning Off Display

### ISSUE THREAD

**Issue by edm00se** [cDima/Aerial#102]
With the screensaver running, it does not adhere to the setting I have for my active power plan, specifically "turn off display", which is set to 30 minutes for the power plan while on AC power.

Windows 7 Pro
release v5.1

**Comment by alistairmcmillan** [comment]
@edm00se Are you running an old version? There was a bug with this back in 2015, but Dmitry fixed it with this commit https://github.com/cDima/Aerial/commit/f802083832b5dca149e2c68b08259f12140f47a5.

You can find the latest release here... https://github.com/cDima/Aerial/releases

**Comment by edm00se** [comment]
I'll be buggered. The version shown in the screen saver settings says "v3".

**Comment by edm00se** [comment]
I'm trying now with the version from [the v5 release](https://github.com/cDima/Aerial/releases/tag/v5). I'll let you know how it goes.

**Comment by edm00se** [comment]
@alistairmcmillan The files from the [.zip in the v5 release](https://github.com/cDima/Aerial/releases/tag/v5) work correctly and my display sleeps according to my settings. Please check the [v5.1 release](https://github.com/cDima/Aerial/releases/tag/v5.1) build assets; they don't appear to be working correctly for me. I'll stay on v5.

**Comment by cDima** [comment]
@edm00se thanks for confirming, we'll try to add better versioning into the settings screen.

**Comment by edm00se** [comment]
@cDima That's good and all, though I was more concerned that the zip contained on the release for v5.1 contained a version of things which, when installed, did not work, as I outlined when opening this issue. I am currently using the v5(.0) release, which works great, and will continue to do so. If there's something wrong with the v5.1 release, I wanted to make sure it was known. Thanks.

**Comment by edm00se** [comment]
Great. It looks like I missed that v6 and v6.1 were released. I'll give v6.1 a try and try and confirm that my issue was resolved. Thanks!

**Comment by subhead** [comment]
i still have this issue with the latest v6. version. any thing i can do?
